### ISSUE TITLE
Laravel 8.x compatibility

### ISSUE THREAD

**Issue by patrickjmeurer** [mxl/laravel-job#2]
Hey!

Have you tested it on Laravel 8.x?

If not, i'm gonna help you with that.

Thanks! :)

**Comment by mxl** [comment]
Hi! No, I didn't. It would be nice if you'll help me with that.

**Comment by patrickjmeurer** [comment]
I did some test in a new fresh install of Laravel 8 and everything worked as expected.

I'm sending a Pull Request to update the package.

#3

**Comment by mxl** [comment]
Closed via #3

**Comment by mxl** [comment]
Released as v1.2.0.
